generate_query:
  description: >
    Generate 10 customer queries (exactly the customer request as it was received through email the Whatsapp Channelm, not the recap 
  expected_output: >
    a list with 10 customer support queries A list with 10 bullet points of the most relevant information about {topic}
  agent: Customer_query_generator

escalate_query:
  description: >
    Rate criticity from 0 to 10 and only pick one to be that requires the intervention from the manager and not the junior agents
  expected_output: >
    The most critical query that require the intervention from the manager and the rating of all the queries
  agent: query_escalation
