research_task:
  description: >
    Conduct a thorough research about {topic}
    The current time is {time}
  expected_output: >
    A list of news articles about {topic} wiith the title, url and snippet ready for senior developers to read
  agent: researcher

reporting_task:
  description: >
    Review the context you got 
    Make sure the report is detailed and contains any and all relevant information technically.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
